package com.a123sold.a123soldinspection.modals;

/**
 * Created by akshit on 29/7/16.
 */
public class HybridformModal {

    Integer CARID;
    Integer HYBRIDCOOLINGSYSTEM;
    Integer SWITCHABLEPOWERTRAINMOUNT;
    Integer HYBRIDENTERTAINMENTANDINFORMATIONDISPLAY;
    Integer POWEROUTLET;
    Float REPAIRINGCOSTHYBRID;
    String COMMENTHYBRID;




    public HybridformModal(Integer CARID, Integer HYBRIDCOOLINGSYSTEM, Integer SWITCHABLEPOWERTRAINMOUNT, Integer HYBRIDENTERTAINMENTANDINFORMATIONDISPLAY, Integer POWEROUTLET, Float REPAIRINGCOSTHYBRID, String COMMENTHYBRID) {
        this.CARID = CARID;
        this.HYBRIDCOOLINGSYSTEM = HYBRIDCOOLINGSYSTEM;
        this.SWITCHABLEPOWERTRAINMOUNT = SWITCHABLEPOWERTRAINMOUNT;
        this.HYBRIDENTERTAINMENTANDINFORMATIONDISPLAY = HYBRIDENTERTAINMENTANDINFORMATIONDISPLAY;
        this.POWEROUTLET = POWEROUTLET;
        this.REPAIRINGCOSTHYBRID = REPAIRINGCOSTHYBRID;
        this.COMMENTHYBRID = COMMENTHYBRID;
    }
    public HybridformModal(){}


    public Integer getHYBRIDCOOLINGSYSTEM() {
        return HYBRIDCOOLINGSYSTEM;
    }

    public Integer getSWITCHABLEPOWERTRAINMOUNT() {
        return SWITCHABLEPOWERTRAINMOUNT;
    }

    public Integer getHYBRIDENTERTAINMENTANDINFORMATIONDISPLAY() {
        return HYBRIDENTERTAINMENTANDINFORMATIONDISPLAY;
    }

    public Integer getPOWEROUTLET() {
        return POWEROUTLET;
    }

    public Float getREPAIRINGCOSTHYBRID() {
        return REPAIRINGCOSTHYBRID;
    }

    public String getCOMMENTHYBRID() {
        return COMMENTHYBRID;
    }


}
